# Generated by Django 4.2.6 on 2023-10-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='book',
            name='long_description',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='short_description',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
