# Generated by Django 4.2.6 on 2023-10-24 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_book_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToReadList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booklist', models.ManyToManyField(to='website.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookstoread', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReadList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booklist', models.ManyToManyField(to='website.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booksread', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
